---
title: vorex
timezone: US/Arizona
collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: vorex Posts
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    comments: true
- scope:
    path: ''
  values:
    layout: default
    show-avatar: true
gems:
- jekyll-feed
url: ''
enforce_ssl: ''
baseurl: "./"
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description. Text
keywords: test1, test2, etc
desc: sample description
avatar: ''
profile:
  name: David Manzer
  email:
  facebook: your-fb-id
  github:
  twitter: your-twitter-id
  linkedin:
  stackoverflow:
pretty-url: vorex.com
disqus: Your-Disqus-Id
google_analytics: Your-GA-Id
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: "/blog/:title"
sass:
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets
  style: compressed
exclude:
- node_modules
- Gruntfile.js
- package.json
created-by: Kaseya
creator-url:
